/*
 * SFTPGo
 * SFTPGo allows you to securely share your files over SFTP and optionally over HTTP/S, FTP/S and WebDAV as well. Several storage backends are supported and they are configurable per-user, so you can serve a local directory for a user and an S3 bucket (or part of it) for another one. SFTPGo also supports virtual folders, a virtual folder can use any of the supported storage backends. So you can have, for example, a user with the S3 backend mapping a Google Cloud Storage bucket (or part of it) on a specified path and an encrypted local filesystem on another one. Virtual folders can be private or shared among multiple users, for shared virtual folders you can define different quota limits for each user. SFTPGo supports groups to simplify the administration of multiple accounts by letting you assign settings once to a group, instead of multiple times to each individual user. The SFTPGo WebClient allows end users to change their credentials, browse and manage their files in the browser and setup two-factor authentication which works with Authy, Google Authenticator and other compatible apps. From the WebClient each authorized user can also create HTTP/S links to externally share files and folders securely, by setting limits to the number of downloads/uploads, protecting the share with a password, limiting access by source IP address, setting an automatic expiration date. 
 *
 * The version of the OpenAPI document: 2.6.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ch.bedag.dap.hellodata.sidecars.sftpgo.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * BandwidthLimit
 */
@JsonPropertyOrder({
  BandwidthLimit.JSON_PROPERTY_SOURCES,
  BandwidthLimit.JSON_PROPERTY_UPLOAD_BANDWIDTH,
  BandwidthLimit.JSON_PROPERTY_DOWNLOAD_BANDWIDTH
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-12-10T09:15:17.190691+01:00[Europe/Warsaw]", comments = "Generator version: 7.9.0")
public class BandwidthLimit {
  public static final String JSON_PROPERTY_SOURCES = "sources";
  private List<String> sources = new ArrayList<>();

  public static final String JSON_PROPERTY_UPLOAD_BANDWIDTH = "upload_bandwidth";
  private Integer uploadBandwidth;

  public static final String JSON_PROPERTY_DOWNLOAD_BANDWIDTH = "download_bandwidth";
  private Integer downloadBandwidth;

  public BandwidthLimit() {
  }

  public BandwidthLimit sources(List<String> sources) {
    
    this.sources = sources;
    return this;
  }

  public BandwidthLimit addSourcesItem(String sourcesItem) {
    if (this.sources == null) {
      this.sources = new ArrayList<>();
    }
    this.sources.add(sourcesItem);
    return this;
  }

  /**
   * Source networks in CIDR notation as defined in RFC 4632 and RFC 4291 for example &#x60;192.0.2.0/24&#x60; or &#x60;2001:db8::/32&#x60;. The limit applies if the defined networks contain the client IP
   * @return sources
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SOURCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getSources() {
    return sources;
  }


  @JsonProperty(JSON_PROPERTY_SOURCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSources(List<String> sources) {
    this.sources = sources;
  }

  public BandwidthLimit uploadBandwidth(Integer uploadBandwidth) {
    
    this.uploadBandwidth = uploadBandwidth;
    return this;
  }

  /**
   * Maximum upload bandwidth as KB/s, 0 means unlimited
   * @return uploadBandwidth
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPLOAD_BANDWIDTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getUploadBandwidth() {
    return uploadBandwidth;
  }


  @JsonProperty(JSON_PROPERTY_UPLOAD_BANDWIDTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUploadBandwidth(Integer uploadBandwidth) {
    this.uploadBandwidth = uploadBandwidth;
  }

  public BandwidthLimit downloadBandwidth(Integer downloadBandwidth) {
    
    this.downloadBandwidth = downloadBandwidth;
    return this;
  }

  /**
   * Maximum download bandwidth as KB/s, 0 means unlimited
   * @return downloadBandwidth
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOWNLOAD_BANDWIDTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDownloadBandwidth() {
    return downloadBandwidth;
  }


  @JsonProperty(JSON_PROPERTY_DOWNLOAD_BANDWIDTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDownloadBandwidth(Integer downloadBandwidth) {
    this.downloadBandwidth = downloadBandwidth;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BandwidthLimit bandwidthLimit = (BandwidthLimit) o;
    return Objects.equals(this.sources, bandwidthLimit.sources) &&
        Objects.equals(this.uploadBandwidth, bandwidthLimit.uploadBandwidth) &&
        Objects.equals(this.downloadBandwidth, bandwidthLimit.downloadBandwidth);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sources, uploadBandwidth, downloadBandwidth);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BandwidthLimit {\n");
    sb.append("    sources: ").append(toIndentedString(sources)).append("\n");
    sb.append("    uploadBandwidth: ").append(toIndentedString(uploadBandwidth)).append("\n");
    sb.append("    downloadBandwidth: ").append(toIndentedString(downloadBandwidth)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

