/*
 * SFTPGo
 * SFTPGo allows you to securely share your files over SFTP and optionally over HTTP/S, FTP/S and WebDAV as well. Several storage backends are supported and they are configurable per-user, so you can serve a local directory for a user and an S3 bucket (or part of it) for another one. SFTPGo also supports virtual folders, a virtual folder can use any of the supported storage backends. So you can have, for example, a user with the S3 backend mapping a Google Cloud Storage bucket (or part of it) on a specified path and an encrypted local filesystem on another one. Virtual folders can be private or shared among multiple users, for shared virtual folders you can define different quota limits for each user. SFTPGo supports groups to simplify the administration of multiple accounts by letting you assign settings once to a group, instead of multiple times to each individual user. The SFTPGo WebClient allows end users to change their credentials, browse and manage their files in the browser and setup two-factor authentication which works with Authy, Google Authenticator and other compatible apps. From the WebClient each authorized user can also create HTTP/S links to externally share files and folders securely, by setting limits to the number of downloads/uploads, protecting the share with a password, limiting access by source IP address, setting an automatic expiration date. 
 *
 * The version of the OpenAPI document: 2.6.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ch.bedag.dap.hellodata.sidecars.sftpgo.client.model;

import java.util.Objects;
import java.util.Arrays;
import ch.bedag.dap.hellodata.sidecars.sftpgo.client.model.EventActionCommandConfig;
import ch.bedag.dap.hellodata.sidecars.sftpgo.client.model.EventActionDataRetentionConfig;
import ch.bedag.dap.hellodata.sidecars.sftpgo.client.model.EventActionEmailConfig;
import ch.bedag.dap.hellodata.sidecars.sftpgo.client.model.EventActionFilesystemConfig;
import ch.bedag.dap.hellodata.sidecars.sftpgo.client.model.EventActionHTTPConfig;
import ch.bedag.dap.hellodata.sidecars.sftpgo.client.model.EventActionIDPAccountCheck;
import ch.bedag.dap.hellodata.sidecars.sftpgo.client.model.EventActionPasswordExpiration;
import ch.bedag.dap.hellodata.sidecars.sftpgo.client.model.EventActionUserInactivity;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * BaseEventActionOptions
 */
@JsonPropertyOrder({
  BaseEventActionOptions.JSON_PROPERTY_HTTP_CONFIG,
  BaseEventActionOptions.JSON_PROPERTY_CMD_CONFIG,
  BaseEventActionOptions.JSON_PROPERTY_EMAIL_CONFIG,
  BaseEventActionOptions.JSON_PROPERTY_RETENTION_CONFIG,
  BaseEventActionOptions.JSON_PROPERTY_FS_CONFIG,
  BaseEventActionOptions.JSON_PROPERTY_PWD_EXPIRATION_CONFIG,
  BaseEventActionOptions.JSON_PROPERTY_USER_INACTIVITY_CONFIG,
  BaseEventActionOptions.JSON_PROPERTY_IDP_CONFIG
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-12-10T09:15:17.190691+01:00[Europe/Warsaw]", comments = "Generator version: 7.9.0")
public class BaseEventActionOptions {
  public static final String JSON_PROPERTY_HTTP_CONFIG = "http_config";
  private EventActionHTTPConfig httpConfig;

  public static final String JSON_PROPERTY_CMD_CONFIG = "cmd_config";
  private EventActionCommandConfig cmdConfig;

  public static final String JSON_PROPERTY_EMAIL_CONFIG = "email_config";
  private EventActionEmailConfig emailConfig;

  public static final String JSON_PROPERTY_RETENTION_CONFIG = "retention_config";
  private EventActionDataRetentionConfig retentionConfig;

  public static final String JSON_PROPERTY_FS_CONFIG = "fs_config";
  private EventActionFilesystemConfig fsConfig;

  public static final String JSON_PROPERTY_PWD_EXPIRATION_CONFIG = "pwd_expiration_config";
  private EventActionPasswordExpiration pwdExpirationConfig;

  public static final String JSON_PROPERTY_USER_INACTIVITY_CONFIG = "user_inactivity_config";
  private EventActionUserInactivity userInactivityConfig;

  public static final String JSON_PROPERTY_IDP_CONFIG = "idp_config";
  private EventActionIDPAccountCheck idpConfig;

  public BaseEventActionOptions() {
  }

  public BaseEventActionOptions httpConfig(EventActionHTTPConfig httpConfig) {
    
    this.httpConfig = httpConfig;
    return this;
  }

  /**
   * Get httpConfig
   * @return httpConfig
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HTTP_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EventActionHTTPConfig getHttpConfig() {
    return httpConfig;
  }


  @JsonProperty(JSON_PROPERTY_HTTP_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHttpConfig(EventActionHTTPConfig httpConfig) {
    this.httpConfig = httpConfig;
  }

  public BaseEventActionOptions cmdConfig(EventActionCommandConfig cmdConfig) {
    
    this.cmdConfig = cmdConfig;
    return this;
  }

  /**
   * Get cmdConfig
   * @return cmdConfig
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CMD_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EventActionCommandConfig getCmdConfig() {
    return cmdConfig;
  }


  @JsonProperty(JSON_PROPERTY_CMD_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCmdConfig(EventActionCommandConfig cmdConfig) {
    this.cmdConfig = cmdConfig;
  }

  public BaseEventActionOptions emailConfig(EventActionEmailConfig emailConfig) {
    
    this.emailConfig = emailConfig;
    return this;
  }

  /**
   * Get emailConfig
   * @return emailConfig
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMAIL_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EventActionEmailConfig getEmailConfig() {
    return emailConfig;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmailConfig(EventActionEmailConfig emailConfig) {
    this.emailConfig = emailConfig;
  }

  public BaseEventActionOptions retentionConfig(EventActionDataRetentionConfig retentionConfig) {
    
    this.retentionConfig = retentionConfig;
    return this;
  }

  /**
   * Get retentionConfig
   * @return retentionConfig
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RETENTION_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EventActionDataRetentionConfig getRetentionConfig() {
    return retentionConfig;
  }


  @JsonProperty(JSON_PROPERTY_RETENTION_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRetentionConfig(EventActionDataRetentionConfig retentionConfig) {
    this.retentionConfig = retentionConfig;
  }

  public BaseEventActionOptions fsConfig(EventActionFilesystemConfig fsConfig) {
    
    this.fsConfig = fsConfig;
    return this;
  }

  /**
   * Get fsConfig
   * @return fsConfig
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FS_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EventActionFilesystemConfig getFsConfig() {
    return fsConfig;
  }


  @JsonProperty(JSON_PROPERTY_FS_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFsConfig(EventActionFilesystemConfig fsConfig) {
    this.fsConfig = fsConfig;
  }

  public BaseEventActionOptions pwdExpirationConfig(EventActionPasswordExpiration pwdExpirationConfig) {
    
    this.pwdExpirationConfig = pwdExpirationConfig;
    return this;
  }

  /**
   * Get pwdExpirationConfig
   * @return pwdExpirationConfig
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PWD_EXPIRATION_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EventActionPasswordExpiration getPwdExpirationConfig() {
    return pwdExpirationConfig;
  }


  @JsonProperty(JSON_PROPERTY_PWD_EXPIRATION_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPwdExpirationConfig(EventActionPasswordExpiration pwdExpirationConfig) {
    this.pwdExpirationConfig = pwdExpirationConfig;
  }

  public BaseEventActionOptions userInactivityConfig(EventActionUserInactivity userInactivityConfig) {
    
    this.userInactivityConfig = userInactivityConfig;
    return this;
  }

  /**
   * Get userInactivityConfig
   * @return userInactivityConfig
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_INACTIVITY_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EventActionUserInactivity getUserInactivityConfig() {
    return userInactivityConfig;
  }


  @JsonProperty(JSON_PROPERTY_USER_INACTIVITY_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserInactivityConfig(EventActionUserInactivity userInactivityConfig) {
    this.userInactivityConfig = userInactivityConfig;
  }

  public BaseEventActionOptions idpConfig(EventActionIDPAccountCheck idpConfig) {
    
    this.idpConfig = idpConfig;
    return this;
  }

  /**
   * Get idpConfig
   * @return idpConfig
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IDP_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EventActionIDPAccountCheck getIdpConfig() {
    return idpConfig;
  }


  @JsonProperty(JSON_PROPERTY_IDP_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdpConfig(EventActionIDPAccountCheck idpConfig) {
    this.idpConfig = idpConfig;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BaseEventActionOptions baseEventActionOptions = (BaseEventActionOptions) o;
    return Objects.equals(this.httpConfig, baseEventActionOptions.httpConfig) &&
        Objects.equals(this.cmdConfig, baseEventActionOptions.cmdConfig) &&
        Objects.equals(this.emailConfig, baseEventActionOptions.emailConfig) &&
        Objects.equals(this.retentionConfig, baseEventActionOptions.retentionConfig) &&
        Objects.equals(this.fsConfig, baseEventActionOptions.fsConfig) &&
        Objects.equals(this.pwdExpirationConfig, baseEventActionOptions.pwdExpirationConfig) &&
        Objects.equals(this.userInactivityConfig, baseEventActionOptions.userInactivityConfig) &&
        Objects.equals(this.idpConfig, baseEventActionOptions.idpConfig);
  }

  @Override
  public int hashCode() {
    return Objects.hash(httpConfig, cmdConfig, emailConfig, retentionConfig, fsConfig, pwdExpirationConfig, userInactivityConfig, idpConfig);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BaseEventActionOptions {\n");
    sb.append("    httpConfig: ").append(toIndentedString(httpConfig)).append("\n");
    sb.append("    cmdConfig: ").append(toIndentedString(cmdConfig)).append("\n");
    sb.append("    emailConfig: ").append(toIndentedString(emailConfig)).append("\n");
    sb.append("    retentionConfig: ").append(toIndentedString(retentionConfig)).append("\n");
    sb.append("    fsConfig: ").append(toIndentedString(fsConfig)).append("\n");
    sb.append("    pwdExpirationConfig: ").append(toIndentedString(pwdExpirationConfig)).append("\n");
    sb.append("    userInactivityConfig: ").append(toIndentedString(userInactivityConfig)).append("\n");
    sb.append("    idpConfig: ").append(toIndentedString(idpConfig)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

