/*
 * SFTPGo
 * SFTPGo allows you to securely share your files over SFTP and optionally over HTTP/S, FTP/S and WebDAV as well. Several storage backends are supported and they are configurable per-user, so you can serve a local directory for a user and an S3 bucket (or part of it) for another one. SFTPGo also supports virtual folders, a virtual folder can use any of the supported storage backends. So you can have, for example, a user with the S3 backend mapping a Google Cloud Storage bucket (or part of it) on a specified path and an encrypted local filesystem on another one. Virtual folders can be private or shared among multiple users, for shared virtual folders you can define different quota limits for each user. SFTPGo supports groups to simplify the administration of multiple accounts by letting you assign settings once to a group, instead of multiple times to each individual user. The SFTPGo WebClient allows end users to change their credentials, browse and manage their files in the browser and setup two-factor authentication which works with Authy, Google Authenticator and other compatible apps. From the WebClient each authorized user can also create HTTP/S links to externally share files and folders securely, by setting limits to the number of downloads/uploads, protecting the share with a password, limiting access by source IP address, setting an automatic expiration date. 
 *
 * The version of the OpenAPI document: 2.6.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ch.bedag.dap.hellodata.sidecars.sftpgo.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GenerateAdminTotpSecret200Response
 */
@JsonPropertyOrder({
  GenerateAdminTotpSecret200Response.JSON_PROPERTY_CONFIG_NAME,
  GenerateAdminTotpSecret200Response.JSON_PROPERTY_ISSUER,
  GenerateAdminTotpSecret200Response.JSON_PROPERTY_SECRET,
  GenerateAdminTotpSecret200Response.JSON_PROPERTY_URL,
  GenerateAdminTotpSecret200Response.JSON_PROPERTY_QR_CODE
})
@JsonTypeName("generate_admin_totp_secret_200_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-12-10T09:15:17.190691+01:00[Europe/Warsaw]", comments = "Generator version: 7.9.0")
public class GenerateAdminTotpSecret200Response {
  public static final String JSON_PROPERTY_CONFIG_NAME = "config_name";
  private String configName;

  public static final String JSON_PROPERTY_ISSUER = "issuer";
  private String issuer;

  public static final String JSON_PROPERTY_SECRET = "secret";
  private String secret;

  public static final String JSON_PROPERTY_URL = "url";
  private String url;

  public static final String JSON_PROPERTY_QR_CODE = "qr_code";
  private byte[] qrCode;

  public GenerateAdminTotpSecret200Response() {
  }

  public GenerateAdminTotpSecret200Response configName(String configName) {
    
    this.configName = configName;
    return this;
  }

  /**
   * Get configName
   * @return configName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONFIG_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getConfigName() {
    return configName;
  }


  @JsonProperty(JSON_PROPERTY_CONFIG_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConfigName(String configName) {
    this.configName = configName;
  }

  public GenerateAdminTotpSecret200Response issuer(String issuer) {
    
    this.issuer = issuer;
    return this;
  }

  /**
   * Get issuer
   * @return issuer
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ISSUER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIssuer() {
    return issuer;
  }


  @JsonProperty(JSON_PROPERTY_ISSUER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIssuer(String issuer) {
    this.issuer = issuer;
  }

  public GenerateAdminTotpSecret200Response secret(String secret) {
    
    this.secret = secret;
    return this;
  }

  /**
   * Get secret
   * @return secret
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SECRET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSecret() {
    return secret;
  }


  @JsonProperty(JSON_PROPERTY_SECRET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSecret(String secret) {
    this.secret = secret;
  }

  public GenerateAdminTotpSecret200Response url(String url) {
    
    this.url = url;
    return this;
  }

  /**
   * Get url
   * @return url
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(String url) {
    this.url = url;
  }

  public GenerateAdminTotpSecret200Response qrCode(byte[] qrCode) {
    
    this.qrCode = qrCode;
    return this;
  }

  /**
   * QR code png encoded as BASE64
   * @return qrCode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QR_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public byte[] getQrCode() {
    return qrCode;
  }


  @JsonProperty(JSON_PROPERTY_QR_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQrCode(byte[] qrCode) {
    this.qrCode = qrCode;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GenerateAdminTotpSecret200Response generateAdminTotpSecret200Response = (GenerateAdminTotpSecret200Response) o;
    return Objects.equals(this.configName, generateAdminTotpSecret200Response.configName) &&
        Objects.equals(this.issuer, generateAdminTotpSecret200Response.issuer) &&
        Objects.equals(this.secret, generateAdminTotpSecret200Response.secret) &&
        Objects.equals(this.url, generateAdminTotpSecret200Response.url) &&
        Arrays.equals(this.qrCode, generateAdminTotpSecret200Response.qrCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(configName, issuer, secret, url, Arrays.hashCode(qrCode));
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GenerateAdminTotpSecret200Response {\n");
    sb.append("    configName: ").append(toIndentedString(configName)).append("\n");
    sb.append("    issuer: ").append(toIndentedString(issuer)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    qrCode: ").append(toIndentedString(qrCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

