--
-- Copyright © 2024, Kanton Bern
-- All rights reserved.
--
-- Redistribution and use in source and binary forms, with or without
-- modification, are permitted provided that the following conditions are met:
--     * Redistributions of source code must retain the above copyright
--       notice, this list of conditions and the following disclaimer.
--     * Redistributions in binary form must reproduce the above copyright
--       notice, this list of conditions and the following disclaimer in the
--       documentation and/or other materials provided with the distribution.
--     * Neither the name of the <organization> nor the
--       names of its contributors may be used to endorse or promote products
--       derived from this software without specific prior written permission.
--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
-- ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
-- WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
-- DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
-- DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
-- (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
-- LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
-- ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-- (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
-- SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--

-- Generated by dbtvault.

    -- Generated by dbtvault.

WITH source_data AS (
    SELECT a.date_pk, a.date_id, a.date, a.year, a.quarter, a.month, a.week, a.day_of_quarter, a.day_of_month, a.day_of_week, a.day_of_year, a.day_is_weekend, a.day_name, a.month_name, a.first_day_of_week, a.last_day_of_week, a.first_day_of_month, a.last_day_of_month, a.first_day_of_quarter, a.last_day_of_quarter, a.first_day_of_year, a.last_day_of_year, a.n_days_in_month, a.load_date, a.record_source
    FROM "postgres"."common_dimension_stg"."stg_date" AS a
    WHERE a.date_pk IS NOT NULL
),

records_to_insert AS (
    SELECT DISTINCT stage.date_pk, stage.date_id, stage.date, stage.year, stage.quarter, stage.month, stage.week, stage.day_of_quarter, stage.day_of_month, stage.day_of_week, stage.day_of_year, stage.day_is_weekend, stage.day_name, stage.month_name, stage.first_day_of_week, stage.last_day_of_week, stage.first_day_of_month, stage.last_day_of_month, stage.first_day_of_quarter, stage.last_day_of_quarter, stage.first_day_of_year, stage.last_day_of_year, stage.n_days_in_month, stage.load_date, stage.record_source
    FROM source_data AS stage
)

SELECT * FROM records_to_insert